apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-deployment
  namespace: notes-namespace
  labels:
    app: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
        - name: notescontainer
          image: mansoor7867/ntim:latest
          ports:
           - containerPort: 8000
